### ISSUE TITLE
add swats

### ISSUE THREAD

**Issue by sailfish009** [jettify/pytorch-optimizer#151]
Adam_SGD:

"SWATS from Keskar & Socher (2017) a high-scoring paper by ICLR in 2018, a method proposed to automatically switch from Adam to SGD for better generalization performance. The idea of the algorithm itself is very simple. It uses Adam, which works well despite minimal tuning, but after learning until a certain stage, it is taken over by SGD."

https://github.com/Mrpatekful/swats

**Comment by jettify** [comment]
FYI https://github.com/jettify/pytorch-optimizer/pull/178
