### ISSUE TITLE
Add AdaBelief

### ISSUE THREAD

**Issue by Erotemic** [jettify/pytorch-optimizer#208]
This new NeurIPS 2020 optimizer looks interesting: https://www.reddit.com/r/MachineLearning/comments/jc1fp2/r_neurips_2020_spotlight_adabelief_optimizer/

The code is already pip installable, so and it looks like it would be easy to integrate into this package: 
https://github.com/juntang-zhuang/Adabelief-Optimizer

**Comment by jettify** [comment]
Done via #209 #210
