### ISSUE TITLE
What is decay factor in Yogi

### ISSUE THREAD

**Issue by bhardwaj1230** [jettify/pytorch-optimizer#212]
I was going through the paper, and they have mentioned the decay factor 0.7 or 0.5. For example Table:2 caption https://papers.nips.cc/paper/8186-adaptive-methods-for-nonconvex-optimization.pdf
Can you please help me to understand that part and how can I add that variable ?

**Comment by jettify** [comment]
I think that decay factor is parameter of `ReduceLROnPlateau`, it has nothing to do with optimizer.
