### ISSUE TITLE
Removing python3.5 support

### ISSUE THREAD

**Issue by jettify** [jettify/pytorch-optimizer#229]
Since python3.5 is no longer supported and python3.9, I am thinking about dropping support for py3.5 in nearest future.
```
Python 3.5 has now reached its end-of-life and has been retired. No more releases will be made.
```
https://www.python.org/dev/peps/pep-0478/

**Comment by jettify** [comment]
cc @iiSeymour

**Comment by iiSeymour** [comment]
I'm gearing up to drop py3.5 soon so this is fine by me.
