### ISSUE TITLE
If I used torch_optimizer in my research, how should i cite it?

### ISSUE THREAD

**Issue by codewithzichao** [jettify/pytorch-optimizer#356]

**Comment by jettify** [comment]
Added citation information to the REAMDE, and citation file, so you can use dedicated github button.
<img width="456" alt="Screen Shot 2021-10-02 at 19 21 49" src="https://user-images.githubusercontent.com/223335/135734186-aa2112bb-4ab3-4af0-9c16-64808db7e03c.png">
