### ISSUE TITLE
Code for Convergence Testing/ Visualization on synthetic functions

### ISSUE THREAD

**Issue by digantamisra98** [jettify/pytorch-optimizer#54]
Hello

Can you please share the code for testing optimizers on synthetic functions which you have used and visualized in the readme?

Thanks!

**Comment by jettify** [comment]
Sure, will do this soon. I was planning to do that  anyway.

**Comment by digantamisra98** [comment]
@jettify Thank you! :)

**Comment by jettify** [comment]
Done via https://github.com/jettify/pytorch-optimizer/pull/56
