### ISSUE TITLE
Minor modification in diffGrad

### ISSUE THREAD

**Issue by shivram1987** [jettify/pytorch-optimizer#55]
Please replace state['previous_grad'] = grad with state['previous_grad'] = grad.clone() in line 117.

**Comment by jettify** [comment]
Thanks! Would you like to submit PR?

**Comment by jettify** [comment]
Fixed via https://github.com/jettify/pytorch-optimizer/pull/57

**Comment by shivram1987** [comment]
Please submit PR...

**Comment by jettify** [comment]
@shivram1987 no problem, just wanted to check if you want to do that yourself :)  @lucidrains helped with PR.

Thanks for DiffGrad!
