### ISSUE TITLE
Add batch invariant optimizer AdaScale?

### ISSUE THREAD

**Issue by PetrochukM** [jettify/pytorch-optimizer#58]
AdaScale was introduced in this paper: https://openreview.net/forum?id=rygxdA4YPS

The paper showed that the proposed optimizer is able to get the same results across five tasks regardless of the batch size (testing from 32 to 32.8k). Here's the graphic:
![image](https://user-images.githubusercontent.com/7424737/75643073-a06e0700-5bf2-11ea-9267-ac898f278c1e.png)

It'd be nice to have a batch invariant optimizer included.

**Comment by jettify** [comment]
Did not know about it. Would you like to submit a PR? Should be easy todo if there is pytorch reference code. Test infrastructure inplace, you can just use any other optimmizer as example.

**Comment by PetrochukM** [comment]
Sorry, I don't feel too confident in implementing it; however, I'd be excited to use it.

**Comment by jettify** [comment]
Got it, looks like authors did not provide reference implementation.

**Comment by avinashsai** [comment]
@PetrochukM @jettify The paper was rejected. Let's wait for the acceptance else it would be unfair on the authors.

**Comment by jettify** [comment]
Agreed, closing for now.
