### ISSUE TITLE
Is there an earlier version than python35

### ISSUE THREAD

**Issue by LvNianZu** [jettify/pytorch-optimizer#59]
Is there an earlier version than python35

**Comment by jettify** [comment]
Unfortunately not, I decided to start with python3.6/3.7 and support only last 3 major python versions. Only modern feature I use is `f` strings. 

If there is lost of demand, library can be extended to 3.5.

**Comment by jettify** [comment]
Closing  this one, feel free to create new issue if you have more questions.

**Comment by jettify** [comment]
New version with python3.5 support, is available on PyPI https://pypi.org/project/torch-optimizer/0.0.1a10/ 
For more information see https://github.com/jettify/pytorch-optimizer/pull/85
