### ISSUE TITLE
Add Ranger optimizer

### ISSUE THREAD

**Issue by tkon3** [jettify/pytorch-optimizer#64]
Hello

paper: https://arxiv.org/abs/1908.00700v2
implementation: https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer

Also:
The clamp parameter for the weight_norm (=10) is hardcoded in LAMB, can you add a new parameter to custom it ?
`                weight_norm = p.data.pow(2).sum().sqrt().clamp(0, 10)`
You can use torch.norm(.) to compute the norm.

Thank you.

**Comment by jettify** [comment]
@tkon3 would you like to submit PR with proposed changes to LAMB?

**Comment by jettify** [comment]
As for ranger should be doable, I added `Lookahead` but have not tested it properly.

**Comment by jettify** [comment]
@tkon3 thanks as lot for the PR! will push new version to PyPI, tonight or tomorrow.

**Comment by jettify** [comment]
New version available on PyPI https://pypi.org/project/torch-optimizer/0.0.1a9/

**Comment by mpariente** [comment]
Hi, Ranger and its variants have been implemented [here](https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer). 
I've made a release of this code on PyPI (`pip install asranger`), could it be a dependency?
I can put together a PR tomorow

**Comment by jettify** [comment]
Hi I think this is good idea, I have few questions:
1) is linked repository is source for deployed package?
2) can you add doc and type annotations (like other optimisers here)

As for tests, once new package added as dependency, test suite can be reused.

**Comment by mpariente** [comment]
[My fork](https://github.com/mpariente/Ranger-Deep-Learning-Optimizer) exactly corresponds to the PyPI release. 

Regarding the tests, I can't make Ranger work for the beale, it's pretty frustrating..

**Comment by mpariente** [comment]
Should be closed by #93
