### ISSUE TITLE
Add baseline visualizations

### ISSUE THREAD

**Issue by slckl** [jettify/pytorch-optimizer#71]
I love the illustrations, but I find the absence of any kind of baselines a shame. It'd be nice to see how Adam or SGD do on the example functions and compare them with some of the more fancy optimizers.

Would this be possible?

I can probably run the required experiments myself, if there are no problems.

**Comment by jettify** [comment]
Good point, it is one few line change in visualisations script:

https://github.com/jettify/pytorch-optimizer/blob/d6a52aed822a33583c63a9255069bbeee58e0d59/examples/viz_optimizers.py#L157-L159

**Comment by jettify** [comment]
Current main problem is visualization is that only LR is grid searched, ideally we try to find best combinations of parameter per optimizer.

PR and improvements are very Wellcome! Code should be easy to run if not let me know I will document it better and fix issues.

**Comment by slckl** [comment]
Did a quick rerun of visualization script with Adam and SGD added. See below.
However, I get different results with all the other optimizers as well, compared to repo. I redid it another time, and it stayed the same as in the first, i.e., specific to my machine, but not matching the repo.

The main winners still seem to be Yogi and RAdam, but others varied more. I'm attaching a pic with AdaBound doing (slightly) worse than in the repo as an example.

If per-machine variability is ok, I can create a PR with the viz code changes and add baseline Adam/SGD images to Readme.

Baselines
![rastrigin_Adam](https://user-images.githubusercontent.com/8687127/76151229-55089c80-60bb-11ea-9cbb-9740a0bd3a61.png)
![rastrigin_SGD](https://user-images.githubusercontent.com/8687127/76151231-56d26000-60bb-11ea-9237-276b9b62b2e3.png)
![rosenbrock_Adam](https://user-images.githubusercontent.com/8687127/76151232-58038d00-60bb-11ea-9d41-89f19a9f4289.png)
![rosenbrock_SGD](https://user-images.githubusercontent.com/8687127/76151235-589c2380-60bb-11ea-95a6-b311306c9f50.png)

AdaBound difference example
What's in the repo:
![rastrigin_AdaBound](https://raw.githubusercontent.com/jettify/pytorch-optimizer/master/docs/rastrigin_AccSGD.png)
What I get:
![rastrigin_AdaBound](https://user-images.githubusercontent.com/8687127/76151322-7d44cb00-60bc-11ea-9b88-5296a33c9634.png)

**Comment by jettify** [comment]
If you change gradient clip to `1.0`, you should have identical results.
https://github.com/jettify/pytorch-optimizer/blob/697fdb1b621d4a741a52310ae740bc434a595d98/examples/viz_optimizers.py#L42

It is very hard to tell which optimizer is better since it depends on data a lot, and on bunch of hyper parameters.

**Comment by jettify** [comment]
Thanks!
(fixed via https://github.com/jettify/pytorch-optimizer/pull/80)
